package types

// Defines table names
const (
	TableOvergoldChainWalletsSetCreateUserWalletPrice = "overgold_chain_wallets_set_create_user_wallet_price"
	TableOvergoldChainWalletsCreateWallet             = "overgold_chain_wallets_create_wallet"
)

// Defines fields
const (
	FieldAccountAddress        = "account_address"
	FieldAccountHash           = "account_hash"
	FieldAddress               = "address"
	FieldAffiliation           = "affiliation"
	FieldAffiliationHash       = "affiliation_hash"
	FieldAffiliationKind       = "affiliation_kind"
	FieldAmount                = "amount"
	FieldAsset                 = "asset"
	FieldBalance               = "balance"
	FieldBurned                = "burned"
	FieldCreator               = "creator"
	FieldDefaultStatus         = "default_status"
	FieldExtras                = "extras"
	FieldFee                   = "fee"
	FieldFeePercent            = "fee_percent"
	FieldHash                  = "hash"
	FieldHolderWallet          = "holder_wallet"
	FieldHolderWalletExtras    = "holder_wallet_extras"
	FieldID                    = "id"
	FieldInCirculation         = "in_circulation"
	FieldIssued                = "issued"
	FieldIssuer                = "issuer"
	FieldKind                  = "kind"
	FieldKinds                 = "kinds"
	FieldName                  = "name"
	FieldNewAddress            = "new_address"
	FieldOldAddress            = "old_address"
	FieldPolicies              = "policies"
	FieldPrecision             = "precision"
	FieldPublicKey             = "public_key"
	FieldReason                = "reason"
	FieldRefRewardWallet       = "ref_reward_wallet"
	FieldRefRewardWalletExtras = "ref_reward_wallet_extras"
	FieldReferrerHash          = "referrer_hash"
	FieldState                 = "state"
	FieldTimestamp             = "timestamp"
	FieldTxHash                = "tx_hash"
	FieldTransactionHash       = "transaction_hash"
	FieldWallet                = "wallet"
	FieldWalletFrom            = "wallet_from"
	FieldWalletTo              = "wallet_to"
	FieldWallets               = "wallets"
	FieldWithdrawn             = "withdrawn"
	FieldBlock                 = "block"
	FieldHeight                = "height"
	FieldNumTxs                = "num_txs"
	FieldTotalGas              = "total_gas"
	FieldProposerAddress       = "proposer_address"
	FieldSuccess               = "success"
)
