package types

// Defines fields
const (
	FieldAccountAddress        = "account_address"
	FieldKind                  = "kind"
	FieldBalance               = "balance"
	FieldExtras                = "extras"
	FieldDefaultStatus         = "default_status"
	FieldAddress               = "address"
	FieldID                    = "id"
	FieldHash                  = "hash"
	FieldCreator               = "creator"
	FieldState                 = "state"
	FieldReason                = "reason"
	FieldKinds                 = "kinds"
	FieldPublicKey             = "public_key"
	FieldHolderWallet          = "holder_wallet"
	FieldRefRewardWallet       = "ref_reward_wallet"
	FieldHolderWalletExtras    = "holder_wallet_extras"
	FieldRefRewardWalletExtras = "ref_reward_wallet_extras"
	FieldReferrerHash          = "referrer_hash"
	FieldExtra                 = "extras"
	FieldAccountHash           = "account_hash"
	FieldAffiliationHash       = "affiliation_hash"
	FieldOldAddress            = "old_address"
	FieldNewAddress            = "new_address"
	FieldAffiliationKind       = "affiliation_kind"
	FieldAffiliates            = "affiliates"
	FieldWallets               = "wallets"
)
