package types

// Defines fields
const (
	FieldAccountAddress        = "account_address"
	FieldKind                  = "kind"
	FieldBalance               = "balance"
	FieldDefaultStatus         = "default_status"
	FieldAddress               = "address"
	FieldID                    = "id"
	FieldHash                  = "hash"
	FieldCreator               = "creator"
	FieldState                 = "state"
	FieldReason                = "reason"
	FieldKinds                 = "kinds"
	FieldPublicKey             = "public_key"
	FieldHolderWallet          = "holder_wallet"
	FieldRefRewardWallet       = "ref_reward_wallet"
	FieldHolderWalletExtras    = "holder_wallet_extras"
	FieldRefRewardWalletExtras = "ref_reward_wallet_extras"
	FieldReferrerHash          = "referrer_hash"
	FieldAccountHash           = "account_hash"
	FieldAffiliationHash       = "affiliation_hash"
	FieldOldAddress            = "old_address"
	FieldNewAddress            = "new_address"
	FieldAffiliationKind       = "affiliation_kind"
	FieldAffiliates            = "affiliates"
	FieldWallets               = "wallets"
	FieldAffiliation           = "affiliation"
	FieldExtras                = "extras"
	FieldName                  = "name"
	FieldIssuer                = "issuer"
	FieldPolicies              = "policies"
	FieldPrecision             = "precision"
	FieldFeePercent            = "fee_percent"
	FieldIssued                = "issued"
	FieldBurned                = "burned"
	FieldWithdrawn             = "withdrawn"
	FieldInCirculation         = "in_circulation"
	FieldAsset                 = "asset"
	FieldAmount                = "amount"
	FieldTimestamp             = "timestamp"
	FieldTxHash                = "tx_hash"
	FieldWalletFrom            = "wallet_from"
	FieldWalletTo              = "wallet_to"
)
