pull_request_rules:
  - name: automerge to master with label automerge and branch protection passing
    conditions:
      - "#approved-reviews-by>1"
      - base~=v2/cosmos/
      - label=automerge
    actions:
      merge:
        method: squash
        strict: true
        commit_message: title+body
