development:
  dialect: postgres
  datasource: host=localhost port=5432 user=postgres dbname=juno password=postgres sslmode=disable
  dir: database/schema

dev:
  dialect: postgres
  datasource: host=10.10.1.79 port=5432 user=postgres dbname=juno password=postgres sslmode=disable
  dir: database/schema
